from typing import List, Tuple, Dict, Set

from itertools import product

from qiana.qianaExtension.signature import Signature
from qiana.qianaExtension.patternParsing import SchemeInfo, getAllSchemeInfos

def getAllSchemesInstances(lines : List[str], signature: Signature = None) -> List[str]:
    """Return all instances of formulas defined in the lines parameter.

    Applies the patterns defined in the lines parameter to generate all
    formula instances.

    Args:
        lines: A list of lines defining the formulas/schemes and the patterns
            to apply to them.
        signature: The signature used with the patterns to obtain the final
            list of formulas.

    Returns:
        A list of all the instances of the formulas obtained by applying the
        patterns in lines. These are complete and valid tptp formulas.
    """
    signature = signature if signature else Signature()
    schemeInfos, secondSignature = getAllSchemeInfos(lines)
    signature.extendFromSignature(secondSignature)
    instances = []
    for schemeInfo in schemeInfos:
        instances.extend(getAllInstancesOfFormula(schemeInfo, signature))
    return instances

def getAllInstancesOfFormula(schemeInfo : SchemeInfo, signature : Signature) -> List[str]:
    """Parse the lines of pattern info and return all formula instances generated by applying macro patterns.

    Args:
        schemeInfo: The scheme information containing formula and patterns.
        signature: The signature containing symbol definitions.

    Returns:
        A list of all the instances of the formula obtained by applying the
        patterns in schemeInfo. These are complete and valid tptp formulas.
    """

    swapValues : Dict[str, List[str]] = dict()  # Matches each swap pattern symbol to the list of concrete symbols
    
    # Process symbol targets from SchemeInfo
    for symbol, target in schemeInfo.getSymbolTargets().items():
        if target == "BASE_PREDICATE":
            swapValues[symbol] = signature.getBasePredicates()
        elif target == "BASE_FUNCTION":
            swapValues[symbol] = signature.getBaseFunctions()
        elif target == "ANY_PREDICATE":
            swapValues[symbol] = signature.getAllPredicates()
        elif target == "QIANA_FUNCTION":
            swapValues[symbol] = signature.getAllFunctions()
        elif target == "QUOTED_VARIABLE":
            swapValues[symbol] = signature.getQuotedVars()
        else:
            raise ValueError(f"Unknown target type: {target}")
        
    # Obtain a list of dicts, each corresponding to one possible mapping of swap pattern symbols to the appropriate concrete symbols
    allCombinations : List[Dict[str,str]] = [dict(zip(swapValues.keys(), combi)) for combi in product(*swapValues.values())]
    allCombinations = [schemeInfo.enrichSymbolDict(case) for case in allCombinations]
    allCombinations = [case for case in allCombinations if schemeInfo.testValidCase(case, signature)] 

    formulas = []
    if not allCombinations and not schemeInfo.containsSwapPatterns(): allCombinations = [dict()] # If there is no swap pattern we still need to generate a formula. However if there is no valid combaination but there is a swap pattern, we generate nothing at all
    for case in allCombinations:
        arities = [signature.getArity(case[symbol]) for symbol in schemeInfo.getAritySymbols()]
        schemeBody = schemeInfo.getBody()
        schemeBody = applyAllPatternsOneInstance(schemeBody, arities, case)
        schemeBody = "fof(" + schemeInfo.getName() + ("_" if case.values() else "") + "_".join(case.values()) + ",axiom," + schemeBody + ")."
        formulas.append(schemeBody)
    return formulas

def applyAllPatternsOneInstance(formula: str, arities: List[int], swapPatterns: Dict[str, str]) -> str:
    """
    Applies all the patterns to obtain one instance of the formula with all macro-patterns expanded
    """
    formula = replaceAllDotPatterns(formula, arities) #We do the dot patterns first to put swappable symbols in dot patterns. The converse would make no sense, so we lose nothing with this ordering.
    formula = replaceAllSwapPatterns(formula, swapPatterns)
    return formula

def replaceAllSwapPatterns(formula: str, swapPatterns: Dict[str, str]) -> str:
    """Replace all swap pattern symbols in the formula with their target symbols.

    Args:
        formula: A formula body in tptp format with macro patterns.
        swapPatterns: A dictionary mapping symbols to replace (starting with $)
            with their replacement symbols.

    Returns:
        The formula with all instances of swap pattern symbols replaced by
        their target symbols.
    """
    for (targetSymbol, newSymbol) in swapPatterns.items():
        assert targetSymbol[0] == "$"
        formula = formula.replace(targetSymbol, newSymbol)
    return formula


def findDots(formula: str) -> Tuple[int, str] | None:
    """Find the leftmost pattern of three dots surrounded by the same symbol.

    Only works for 3 dots with the same separation symbol at each end. The
    symbol must be one character.

    Args:
        formula: A formula body in tptp format with macro patterns.

    Returns:
        A tuple containing the index of the symbol to the left of the leftmost
        3 dots in formula paired with the separation symbol they use, or None
        if there is no dot pattern.
    """
    for i in range(len(formula) - 2):
        if formula[i] == "." and formula[i + 1] == "." and formula[i + 2] == ".":
            assert formula[i - 1] == formula[i + 3] # check if both ends of the dots have matching separation symbol
            assert formula[i - 1] in [",", "&", "|"] # check if the separation symbol is valid
            return i-1, formula[i - 1]
    return None

def findOperands(formula: str, index: int) -> Tuple[str, str, int, int]:
    """Return the two operands of a series of dots in formula.

    Args:
        formula: A formula body in tptp format with macro patterns.
        index: The index of the symbol to the left of the dot pattern.

    Returns:
        A tuple of size 4 containing the two operands of the dot in formula, and the
        indexes delimiting the range of the operand+3 dots pattern.
    """
    leftStartingIndex = index-1
    while formula[leftStartingIndex] == " ": leftStartingIndex -= 1
    rightStartingIndex = index+5
    while formula[rightStartingIndex] == " ": rightStartingIndex += 1

    # Yes the code bellow can be rewritten in a handful of lines with a for loop and a break, and yes it would avoid the code reuse. Don't.

    iterIndexLeft = leftStartingIndex
    parenthesisCount = 0
    while formula[iterIndexLeft] not in ["(", "[", ",",":"] or parenthesisCount != 0:
        if formula[iterIndexLeft] == ")":
            parenthesisCount += 1
        elif formula[iterIndexLeft] == "(":
            parenthesisCount -= 1
        iterIndexLeft -= 1
        if iterIndexLeft < 0: 
            assert(iterIndexLeft == -1)
            break
    leftOperand = formula[iterIndexLeft+1:leftStartingIndex+1]
    
    iterIndexRight = rightStartingIndex
    parenthesisCount = 0
    while formula[iterIndexRight] not in [")", "]", ",", ":"] or parenthesisCount != 0:
        if formula[iterIndexRight] == ")":
            parenthesisCount += 1
        elif formula[iterIndexRight] == "(":
            parenthesisCount -= 1
        iterIndexRight += 1
        if iterIndexRight >= len(formula):
            assert(iterIndexRight == len(formula))
            break
    rightOperand = formula[rightStartingIndex:iterIndexRight]

    return leftOperand.strip(), rightOperand.strip(), iterIndexLeft+1, iterIndexRight-1

def injectInDifference(firstOperand: str, secondOperand: str, symbolToInject: str) -> str:
    """Inject a symbol in the difference between two almost identical operands.

    Receives two operands that are almost identical except for a counting
    symbol that is "1" in the first operand and "#" in the second operand.

    Args:
        firstOperand: The first operand (contains "1").
        secondOperand: The second operand (contains "#").
        symbolToInject: The symbol to inject in place of "#".

    Returns:
        The second operand with "#" replaced by the symbol to inject.
    """
    assert secondOperand.replace("#","1") == firstOperand
    return secondOperand.replace("#", symbolToInject)

def replaceDotPattern(formula: str, leftOfPattern: int, rightOfPattern: int, separationSymbol: str, leftOperand:str, rightOperand: str, arity: int):
    """Replace a series of dots in formula with the appropriate number of separation symbols.

    Args:
        formula: A formula body in tptp format with macro patterns.
        leftOfPattern: The index of the symbol to the left of the operand to
            the left of the dots.
        rightOfPattern: The index of the symbol to the right of the operand to
            the right of the dots.
        separationSymbol: The symbol used to separate the operands.
        leftOperand: The left operand of the dots.
        rightOperand: The right operand of the dots.
        arity: The number of operands to insert in the series.

    Returns:
        The formula with the dot pattern replaced by the separation symbol and
        repeated operands.
    """
    replaced = separationSymbol.join([injectInDifference(leftOperand, rightOperand, str(i)) for i in range(1, arity+1)])
    return formula[:leftOfPattern] + replaced + formula[rightOfPattern+1:]

def replaceAllDotPatterns(formula: str, arities: List[int]) -> str:
    """Replace all dot patterns in formula with the appropriate number of separation symbols.

    Args:
        formula: A formula body in tptp format with macro patterns.
        arities: The arities of the functions in the formula.

    Returns:
        The formula with all dot patterns replaced by the separation symbol
        and repeated operands.

    Example:
        >>> replaceAllDotPatterns("(wff(t1) &...& wff(tn) => wff(f(t1,...,tn)))", [2, 2])
        "(wff(t1) & wff(t2) => wff(f(t1,t2))"
    """
    for arity in arities:
        assert findDots(formula) is not None
        dotIndex, seprationSymbol = findDots(formula)
        leftOperand, rightOperand, leftIndex, rightIndex = findOperands(formula, dotIndex)
        formula = replaceDotPattern(formula, leftIndex, rightIndex, seprationSymbol, leftOperand, rightOperand, arity)
    return formula